//
// Created by haridev on 10/5/23.
//

#ifndef DFTRACER_CONSTANTS_H
#define DFTRACER_CONSTANTS_H
#define DFTRACER_CONFIGURATION "DFTRACER_CONFIGURATION"
#define DFTRACER_ENABLE "DFTRACER_ENABLE"
#define DFTRACER_GOTCHA_PRIORITY "DFTRACER_GOTCHA_PRIORITY"
#define DFTRACER_LOG_LEVEL "DFTRACER_LOG_LEVEL"
#define DFTRACER_LOG_FILE "DFTRACER_LOG_FILE"
#define DFTRACER_INIT "DFTRACER_INIT"
#define DFTRACER_INIT_COUNT "DFTRACER_INIT_COUNT"
#define DFTRACER_DATA_DIR "DFTRACER_DATA_DIR"
#define DFTRACER_DATA_DIR_DELIMITER ':'
#define DFTRACER_SET_CORE_AFFINITY "DFTRACER_SET_CORE_AFFINITY"
#define DFTRACER_ERROR "DFTRACER_ERROR"
#define DFTRACER_INC_METADATA "DFTRACER_INC_METADATA"
#define DFTRACER_DISABLE_POSIX "DFTRACER_DISABLE_POSIX"
#define DFTRACER_DISABLE_STDIO "DFTRACER_DISABLE_STDIO"
#define DFTRACER_DISABLE_IO "DFTRACER_DISABLE_IO"
#define DFTRACER_TRACE_COMPRESSION "DFTRACER_TRACE_COMPRESSION"
#define DFTRACER_DISABLE_TIDS "DFTRACER_DISABLE_TIDS"
#define DFTRACER_BIND_SIGNALS "DFTRACER_BIND_SIGNALS"
#define DFTRACER_WRITE_BUFFER_SIZE "DFTRACER_WRITE_BUFFER_SIZE"
#define DFTRACER_ALL_FILES "all"

static const int EVENT_TYPE_SIZE = 128;
static const unsigned int DFT_PATH_MAX = 1024 * 4;
static const char SEPARATOR = ';';
static const int HASH_OUTPUT = 16;
#define NO_HASH_DEFAULT 0

#endif  // DFTRACER_CONSTANTS_H
