#!/bin/bash

# The script sanitizes all trace file to mask non-utf characters.
# This has the following signature.
#
# usage: dftracer_sanitize [-fcv] [-d input_directory] [-o output_directory]
#   -f                      override output directory
#   -c                      compress outputs
#   -v                      enable verbose mode
#   -h                      display help
#   -d input_directory      specify input directories. should contain .pfw or .pfw.gz files.
#   -o output_directory     specify output directory.

LOG_DIR=$PWD
OUTPUT_DIR=$PWD/output
override=0
compressed=0

PPWD=$PWD

function usage {
    echo "usage: $(basename $0) [-fcv] [-d input_directory] [-o output_directory]"
    echo "  -f                      override output directory"
    echo "  -c                      compress output file"
    echo "  -v                      enable verbose mode"
    echo "  -h                      display help"
    echo "  -d input_directory      specify input directories. should contain .pfw or .pfw.gz files."
    echo "  -o output_directory     specify output directory."
    exit 1
}
while getopts ':cvfd:o:h' opt; do
  case "$opt" in
    d)
      LOG_DIR="${OPTARG}"
      ;;
    o)
      OUTPUT_DIR="${OPTARG}"
      ;;
    f)
      override=1
      ;;
    v)
      set -x
      ;;
    c)
      compressed=1
      ;;
    h)
      usage
      exit 0
      ;;

    :)
      echo -e "option requires an argument.\n"
      usage
      exit 1
      ;;

    ?)
      echo -e "Invalid command option.\n"
      usage
      exit 1
      ;;
  esac
done
shift "$(($OPTIND -1))"

mkdir -p ${OUTPUT_DIR}

if [ -z "$( ls -A '${OUTPUT_DIR}' )" ] && [ $override -eq 0 ]; then
  echo "The directory is not empty. Please pass a clean directory or pass -f flag."
  exit 0
fi

echo "Setting up output directory"
rm -rf ${OUTPUT_DIR}
mkdir -p ${OUTPUT_DIR}


pfw_count=`ls -1 $LOG_DIR/*.pfw 2> /dev/null | wc -l`
gz_count=`ls -1 $LOG_DIR/*.gz 2> /dev/null | wc -l`
total=$((pfw_count + gz_count))
if [ $total == 0 ]; then
    echo "The folder does not contain any pfw or pfw.gz files."
    exit 0
fi

# loop over logs
for file in "$LOG_DIR"/*.pfw*; do
  # only look at files
  if [ -f "$file" ]; then
    # calculate basename and copy files
    filename=$(basename -- "$file")
    ext="${filename##*.}"
    echo "Extension is $ext"
    cp $LOG_DIR/$filename $OUTPUT_DIR/.tmp.$filename
    if [ "$ext" == "gz" ]; then
      # if file is gz get the name
      name=${filename%.pfw.gz}
      echo "extracted name $name"
      echo "[" > $OUTPUT_DIR/$name.pfw
      # replace non utf characters
      gunzip -c $OUTPUT_DIR/.tmp.$filename | LC_ALL=C sed 's/[^[:print:]\r\t]//g' | jq -R -c "fromjson?" >> $OUTPUT_DIR/$name.pfw
      echo "]" >> $OUTPUT_DIR/$name.pfw
      # compress
      if [ $compressed == 1 ]; then
        gzip $OUTPUT_DIR/$name.pfw
        echo "Processed $OUTPUT_DIR/$name.pfw.gz"
      else
        echo "Processed $OUTPUT_DIR/$name.pfw"
      fi
    else
      # if file is pfw get the name
      name=${filename%.pfw}
      echo "extracted name $name"
      # replace non utf characters and valid json lines
      echo "[" > $OUTPUT_DIR/$name.pfw
      LC_ALL=C sed 's/[^[:print:]\r\t]//g' $OUTPUT_DIR/.tmp.$filename | jq -R -c "fromjson?" >> $OUTPUT_DIR/$name.pfw
      echo "]" >> $OUTPUT_DIR/$name.pfw
      if [ $compressed == 1 ]; then
        gzip $OUTPUT_DIR/$name.pfw
        echo "Processed $OUTPUT_DIR/$name.pfw.gz"
      else
        echo "Processed $OUTPUT_DIR/$name.pfw"
      fi
    fi    
    # remove temp file
    rm $OUTPUT_DIR/.tmp.$filename
  fi
done
